services:
  - type: web
    name: pdf-search-api
    env: python
    buildCommand: pip install -r requirements_minimal.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app_minimal:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false
